### ISSUE TITLE
Socks5 support

### ISSUE THREAD

**Issue by PMontalvo** [drallieiv/KinanCity#11]
Tried making accounts using socks5 proxies.  The proxies are good, used them in PT in the past format there was socks5://IP:port

**Comment by drallieiv** [comment]
TODO : replace current proxy config parameter parsing `Configuration::loadProxies` by a more advanced parsing

regexp : http://regexr.com/3flvp

**Comment by drallieiv** [comment]
Forgot to notice you but socks support is almost complete.
It works internally (and with server) but I have to switch that on command line too.

**Comment by PMontalvo** [comment]
Thank you, when it goes live I will test it out.

**Comment by drallieiv** [comment]
@PMontalvo plase test PR #17 DM me on discord if you need
