### ISSUE TITLE
Can't get any proxy working

### ISSUE THREAD

**Issue by chrille331** [drallieiv/KinanCity#129]
I've tried lots of different proxy server lists, http, https, socks etc. from different sites both paid and free. None work, what am I doing wrong?
Getting these messages for all proxies:
Error, received HTTP 403
or this
Proxy test for http://67.212.186.101:80 failed, remove proxy

**Comment by drallieiv** [comment]
You need IP that are not banned by PTC. Which usually means not a datacenter IP but a residential or mobile IP.
