### ISSUE TITLE
can you add CaptchaAI

### ISSUE THREAD

**Issue by CaptchaAI** [drallieiv/KinanCity#137]
Hi,
You added CaptchaAI for captcha option which is not referring to our services, and this confusing our clients
CaptchaAI.io changed there name to CapSolver
So if you can Please fix this
and also if you can add CaptchaAI option
We are the same as 2Captcha API
https://captchaai.com/api-docs.php

Regards,

**Comment by drallieiv** [comment]
Name has been updated and we talked about that confusion in the discord

**Comment by drallieiv** [comment]
Note, your implementation do not work with 2captcha API batch requests.
