### ISSUE TITLE
keep getting IP throotle

### ISSUE THREAD

**Issue by ghost** [drallieiv/KinanCity#16]
everything is working but i keep getting that "Email Error, this could be IP throttle, consider as Account Rate Limited".
i've read the documentation but can't find a solution (-nl didn't help), what can i do?

**Comment by drallieiv** [comment]
`-nl` will remove the management of the pausing/switching system to comply with the 5 creations per 10 minutes. So don't use it, unless you manage your own IP switching.

Please give us the command line parameter you used (without the passwords and proxy auth)

And try to create and account manually with the same data on nintendo website.

**Comment by ghost** [comment]
i used 'java -jar KinanCity-core-1.2.0-SNAPSHOT.jar -m mymail@outlook.com -f g**rocket -p mypw -c 10 -ck mykey -nl'

**Comment by drallieiv** [comment]
If you stay on the same IP then you will be sending more then 5 request per 10 minutes with that configuration and PTC will refuse your creations.
