### ISSUE TITLE
Make account creation 5 accounts per 15 minutes

### ISSUE THREAD

**Issue by ghost** [drallieiv/KinanCity#18]
Prior research was done by PalletTown author to identify that account creation was limited to 5 accounts per 15 minutes.

Currently Kinan city is doing 5 per 10 minutes and I believe this is causing burned 2captcha.

I would recommend increasing time to 5 accounts per 15 minutes unless it is certain that PT author's prior research is wrong, but I don't think it is wrong from what I've experienced.

**Comment by drallieiv** [comment]
I'll switch default value to 15 for everyone. Just as a fix, no custom parameters for now.

**Comment by drallieiv** [comment]
Also i'll boost the margin to 60s to match max 2 captcha's response time.
It will end up with slower total time, but should waste less captcha.

GUI will allow people to use their own settings to choose between speed and cost-effectiveness

**Comment by ghost** [comment]
Good man :)
