### ISSUE TITLE
Proxy username with @ symbol fails check.

### ISSUE THREAD

**Issue by higden** [drallieiv/KinanCity#23]
Version: https://github.com/drallieiv/KinanCity/releases/tag/v1.3.1-rc2 (latest)

I think this is the same issue as  #21.

If a username has an "@" symbol in it (e.g. an email address), the proxy can't be loaded.

Example: 
```
java -jar KinanCity-core-1.3.1-SNAPSHOT.jar -px 'email@email.com:pRoXyPaSs@my.proxy.com:80' -m 'email@email.com' -f 'a**b' -c 1 -s 1 -p 'p4ssw0rD!'

INFO  [Kinan City]  -- Start Kinan City CLI -- 
WARN  [Kinan City] Cannot load URI [email@email.com:pRoXyPaSs@my.proxy.com:80] as a HTTP Proxy
ERROR [Kinan City] Invalid proxy email@email.com:pRoXyPaSs@my.proxy.com:80
```

**Comment by drallieiv** [comment]
Yes it is the same issue then #21 url unsafe characters in login and password should be encoded with % followed by a 2 digit hex value of the UTF8 character.

`%` is currently forbidden as defined by the proxy definition regular expression and should not.

test case : `@` encoded as `%40` should be allowed by regular expression.
