### ISSUE TITLE
Created user is uderage

### ISSUE THREAD

**Issue by Ragon91** [drallieiv/KinanCity#24]
I created a couple of account with a dropmail.me e-mail address cause they support the + e-mail trick, but all of them turned out to be underage accounts.

**Comment by drallieiv** [comment]
Please provide logs and a description on how to reproduce the bug.

**Comment by drallieiv** [comment]
Current Date of Birth is hardcoded to 1985-01-16, wich makes someone 32 years old.
It should not be hardcoded ( #25 ) but it does not make underage account either.

**Comment by drallieiv** [comment]
Without any response from reporter @Ragon91 . i'm closing this one
