### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by xLeevo** [drallieiv/KinanCity#28]
http://puu.sh/vL96f/e5a5b8cc5c.png

Is this a known issue? im on the latest java version using windows, proxy are 100% available

**Comment by drallieiv** [comment]
That is not a known error, plus KinanCity is not using django at all.

Also it's just 1 line of logs, so we can't do anything with that.

**Comment by xLeevo** [comment]
http://puu.sh/vLA6n/557a1823a8.png 
Its weird if KinanCity isnt using django, because i just started it like the other guys i asked

**Comment by K4N3R** [comment]
@ xLeevo try reducing the ptc account name to less than 16 characters.
I have had some success with that.

**Comment by drallieiv** [comment]
multiple django error reports all seems to converge to username lenght
closing issue and continuing in #34
