### ISSUE TITLE
[mail] BUG: Some validations reported as failed shows as already activated when retried.

### ISSUE THREAD

**Issue by ISsmt** [drallieiv/KinanCity#30]
Sometimes i get this error in kinancity-mail
ERROR KcMessageHandler: Account activation for email account@mail.com : failed

If I insert the link manually into the browser, says the website "Your account has already been activated"

**Comment by drallieiv** [comment]
In that case the url should be in the log for you to be able to use it manually.

I may look at adding bigger timeout or even a retry mechanism.

**Comment by drumm2k** [comment]
I have same issue, it worked well for ~200 accs, then its always fails and i need manually copy/paste links from terminal to activate them. Tried to restart Kinan-Mail, doesn't help.

**Comment by drallieiv** [comment]
If it does not say  "Your account has already been activated", then it's not the same error
