### ISSUE TITLE
Error creating accounts

### ISSUE THREAD

**Issue by Darknite24** [drallieiv/KinanCity#33]
This morning I started getting the error: django.utils.functional.__proxy__ with each account creation request in the console window for KinanCity-core-1.3.1-SNAPSHOT.jar. Any ideas what this may be?

**Comment by Darknite24** [comment]
Disregard this issue. I had an AHA moment and checked the username I was creating. It was too long and thus throwing the above error.

**Comment by drallieiv** [comment]
So should a length verification be done on the username. What would be the max length

**Comment by Darknite24** [comment]
A quick google search show the username requirements are 4-15 characters. So a verification message would be good to alert users of the issue.
