### ISSUE TITLE
account creation rate limited

### ISSUE THREAD

**Issue by Darknite24** [drallieiv/KinanCity#36]
Can you add a parameter to set the wait time between creating accounts?

**Comment by drallieiv** [comment]
There is a wait time between http requests  here : a3f664c

in the config file
```
# Prevent from using the same IP twice in less then N seconds (default to 5s)
# proxy.bottleneck=5 
```

**Comment by drallieiv** [comment]
there is no wait time required if you change proxy/ip

**Comment by drallieiv** [comment]
Bottleneck has changed since, @Darknite24 is it still an issue ?
