### ISSUE TITLE
Kinan sends default user-agent

### ISSUE THREAD

**Issue by FrostTheFox** [drallieiv/KinanCity#38]
Kinan does not make an attempt to set the user-agent to send to pokemon.com, therefor, you end up with "okhttp/version".

https://thunderfox.nl/sharex/Vj6kWo9Wrg.png

This is very easily a sign on PTC's end, especially with the combined Kinan traffic.

Steps to reproduce:
* Install Fiddler root certificate in Java SSL store.
* Run Kinan with Fiddler as proxy.
* View headers in Fiddler.

Shoutout to Jake McKnight

**Comment by PKMTracker** [comment]
❌❌💰

**Comment by drallieiv** [comment]
I Will add a standard browser user agent

**Comment by drallieiv** [comment]
Some request had the user agent set up, but not all of them.

**Comment by FrostTheFox** [comment]
👍
