### ISSUE TITLE
[ENHANCEMENT] Docker

### ISSUE THREAD

**Issue by bbdoc** [drallieiv/KinanCity#4]
Hi,

Would be very nice if you could add a docker version (such as existing with pikaptcha).

Thanks

**Comment by drallieiv** [comment]
There is not much thing needed to be installed, only Java 8. But I'll do that.

**Comment by drallieiv** [comment]
Or you can submit a PR if you want.

**Comment by drallieiv** [comment]
The thing is I could make a Docker Image that compiles the app and allow it to run.
But travis already compiles the released versions
So I could also make a docker image that just downloads the latest jar and run it

**Comment by bbdoc** [comment]
Cool thanks a lot, will give this a try ;-)

**Comment by drallieiv** [comment]
Docker not up to date and no time to work on it.
Feature indefinaterly delayed unless someone else wants to do it.
