### ISSUE TITLE
support for CC and DOB

### ISSUE THREAD

**Issue by hudecof** [drallieiv/KinanCity#40]
there are hardened values for CC and DOB.
It would be good to be able to specifify these values alebo in accounts.csv format

**Comment by drallieiv** [comment]
They already can be put in the csv, if you also add the right key in the first header line, but documentation about that is missing.

**Comment by hudecof** [comment]
I downloaded the 1.3.2-rc6 and in the code I did not found support for this. Even in master branch it's missing.

I do not see it
* https://github.com/drallieiv/KinanCity/blob/develop/KinanCity-core/src/main/java/com/kinancity/core/CliOptions.java
* https://github.com/drallieiv/KinanCity/blob/develop/KinanCity-core/src/main/java/com/kinancity/core/generator/account/CsvHeaderConstants.java
* https://github.com/drallieiv/KinanCity/blob/develop/KinanCity-core/src/main/java/com/kinancity/core/generator/account/CsvReaderAccountGenerator.java

What are the column names for there values?

**Comment by dshoreman** [comment]
@hudecof `dob` and `country` seemed the most obvious but - although `buildAccountDataFromCsv()` sends all the columns to `buildAccountDataFromMap()` - only username, password and email get populated.

Should be an easy fix. As soon as I've double checked it's working I'll post a PR.
