### ISSUE TITLE
Configuration missing

### ISSUE THREAD

**Issue by ghost** [drallieiv/KinanCity#49]
Using the latest release and these arguments in .bat
-m ... -u ... -p ... -ck ...

config.properties is existing and in the same folder.

06-07 17:26:21 [Kinan City]  -- Start Kinan City CLI -- 
06-07 17:26:21 [Kinan City] Cannot load URI [] as a HTTP Proxy
06-07 17:26:21 [Kinan City] Invalid proxy 
06-07 17:26:21 [Kinan City] ProxyManager setup with 0 proxies : 
06-07 17:26:21 [Kinan City] Create a single account
06-07 17:26:22 [Kinan City] Catpcha Key is valid. Current 2 captcha balance is 10.00556
06-07 17:26:22 [OfficerJenny(BottleNeck)] Starting Bottleneck with a space of 15s between all resources access
06-07 17:26:22 [NurseJoy(Recycler)] Benched proxy recycler started.
06-07 17:26:22 [Kinan City] No valid proxy given
06-07 17:26:22 [Kinan City] Account creation failed, missing configuration

**Comment by drallieiv** [comment]
The bat might have been fixed since. Do you still have that error ?

**Comment by drallieiv** [comment]
closed as there was no response. Please reopen if the issue persist.
