### ISSUE TITLE
Include email address in activation log

### ISSUE THREAD

**Issue by ashleykleynhans** [drallieiv/KinanCity#51]
Thanks for providing such an awesome tool.

It would be great if the mail server could include the email address the mail was sent to as well as the activation link.  It's not really very useful just to see the activation link in the log, you don't know which account that activation link is for.

**Comment by drallieiv** [comment]
The log should currently say : Activation link found  for email ... : [.........]

I'll look to add it to the csv file, but that would require the format to be changed

**Comment by ashleykleynhans** [comment]
Yeah sorry I meant the CSV file (links.log).  The log while its running does include the email address, but I would like it to be included in the CSV file too, to make it easier to identify which accounts have been successfully verified and which have not just by viewing the links.log file.

**Comment by drallieiv** [comment]
merged
