### ISSUE TITLE
Maximum Age not adhered to

### ISSUE THREAD

**Issue by tomballgithub** [drallieiv/KinanCity#60]
The function 'randomAdultDateOfBirth' in  /ptc-api/src/main/java/com/kinancity/api/model/AccountData.java has a maximum age range of 18, 80

```
public static String randomAdultDateOfBirth() {
		return randomDateOfBirth(18, 80);
	}

```
However, in my logs I am seeing ages larger than that.

For example, 97-98 years old:  
```
07-03 19:23:20 [Brock] Create account : AccountData [username=REDACTED, email=REDACTED, password=REDACTED, dob=1920-09-25, country=US]
07-03 19:56:30 [Kiawe] Create account : AccountData [username=REDACTED, email=REDACTED, password=REDACTED, dob=1919-09-06, country=US]

```

This could be easily flagged by Niantic if desired.

**Comment by tomballgithub** [comment]
The issue is this code.  It is subtracting BOTH minAge and up to maxAge from current time.  This is up to 18 + 80 = 98 year old birthday.  

```
int randomDays = RandomUtils.nextInt(maxAge * 365);
LocalDateTime dobDate = LocalDateTime.now().minusYears(minAge).minusDays(randomDays);

```

This line should change to:

`int randomDays = RandomUtils.nextInt((maxAge-minAge) * 365);
`

**Comment by tomballgithub** [comment]
I would also recommend lowering the Max age.   Max 55 would probably suffice for purposes of account generation

**Comment by tomballgithub** [comment]
I changed the above code and it didn't help.

The commit for the random birth date references a routine in::
ptc-api/src/main/java/com/kinancity/api/model/AccountData.java

The comment says dates should be between 1970 and 2000.  Clearly this is not working but the code looks right

```
	private String chooseRandomDateOfBirth() {
		Random generator = new Random();
		// year: 1970 to 2000
		int y = generator.nextInt(30) + 1970;
 +
```

**Comment by tomballgithub** [comment]
@sLoPPydrive

**Comment by drallieiv** [comment]
I agree with the bug and the advised changes. Can you create a pull request for that ?

**Comment by tomballgithub** [comment]
I see the issue with what I pasted above.  This commit changed the code completely which is why what I pasted may be confusing.  The original code should have worked.  New code with this commit is broken. 

@drallieiv
fix: country should be default if not given not null  …
drallieiv committed 29 days ago 
a027928

Not sure how to recompile.
