### ISSUE TITLE
mail server - Could not find or load main class

### ISSUE THREAD

**Issue by WalterMagnum** [drallieiv/KinanCity#8]
Whenever I try to run the mail server v1.0.0, this is the error I get:  "Could not find or load main class com.kinancity.core.KinanCityClient".  I have rarely run a Java module so I could be doing something wrong.  I am using mailserver 1.0.0 because that is the latest version I see in releases.  Am I missing something obvious?  Some very basic instruction added to readme.md would help users such as myself greatly.  Thanks for your time!

**Comment by jophj** [comment]
@WalterMagnum you can start it by specifying the main class while we wait for a fix:
`java -cp KinanCity-mail-1.0.0-SNAPSHOT.jar com.kinancity.mail.MailServerApplication`

**Comment by drallieiv** [comment]
Sorry @WalterMagnum I messed up the build config, will push a patch.

**Comment by drallieiv** [comment]
Fixed in by 6d820c1 in Release 1.2.0-rc2
