### ISSUE TITLE
Imagetyperz invalid captcha id

### ISSUE THREAD

**Issue by granis** [drallieiv/KinanCity#80]
While generating ~100 accounts, I eventually run into this error.
[imageTypers] Unknown I0mageTypers Error : ERROR: INVALID_CAPTCHA_ID

When it is encountered, it seems to loop and continuously output same error until forced-stopped.

**Comment by drallieiv** [comment]
Can't do anything without log file

**Comment by granis** [comment]
That's a good point!
Here's the log just before:

11-25 20:04:37 [imageTypers] Requested new Captcha, id : ERROR: LIMIT_EXCEED
11-25 20:04:42 [imageTypers] Unknown I0mageTypers Error : ERROR: INVALID_CAPTCHA_ID

**Comment by drallieiv** [comment]
@granis should be fixed by 688b8503ca9f0f2ab7600ffd79131ac2014eaf08 in v1.4.2-rc01
