### ISSUE TITLE
Kinan is not loading the Cofig.properties file

### ISSUE THREAD

**Issue by MrHeady** [drallieiv/KinanCity#94]
Kinan is skipping the config file

Kinan always trys to use a imagetypers key.
Configuration Init Failed : com.kinancity.core.captcha.imageTypers.ImageTypersConfigurationException: Authentication failed, captcha key might be bad

i renamed the config.properties and edited it / changed the Provider and pasted the 2captcha key in.

what is wrong?

**Comment by drallieiv** [comment]
Seems that I made a type in the command line arg, making it impossible to change what provider was used in 1.4.2
It should be OK now. Dont hesitate to reach the discord if needed
