### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by The-Phoneboy** [drallieiv/KinanCity#97]
can I change things from kinan.mail.domain.com to domain.com?

**Comment by drallieiv** [comment]
Please be clearer in your issues. I don't understand what your issues is about?

Please state what are you doing, the result your are getting and what your are expecting

**Comment by The-Phoneboy** [comment]
Sorry about that..I am trying to accomplish two things..I would like to specify my domain only when creating my account....I tried to use  my domain.com  to create accounts and the mail server would not recieve...however when i changed it to kinan.mail.mydomain.com, as instructed by my colleague...it wokrs fine...secondly I have a redmail server..I would like to be able to use this make the emails  of the accounts changeable after creation..I am most likely  going about it the wrong way...I am probably over complicating this as well....sorry for the confusion...thanks

**Comment by drallieiv** [comment]
First check that your email server is setup properly. Use https://mxtoolbox.com to see if your domain has an email (A) entry
Then on your Redmond email server, either create all the inbox you plan to use. Or define a catch all rule. Then try to send an email from an external adress.

If that works then go ahead with kinan.

If you want to chat please use discord and keep github for issues
